export const Routes = {
  LoginScreen: 'LoginScreen',
  Home: 'Home',
  ServicesScreen: 'ServicesScreen',
  SettingsScreen: 'SettingsScreen',
  Alerts: 'Alerts',
  MedicalHistory: 'Medical History',
  EpidemiologicalHistoryScreen: 'EpidemiologicalHistoryScreen',
  SocialHistoryScreen: 'SocialHistoryScreen',
  AllergiesScreen: 'AllergiesScreen',
  ProblemsScreen: 'ProblemsScreen',
  DevicesScreen: 'DevicesScreen',
  MedicationSummaryScreen: 'MedicationSummaryScreen',
  GynecologicalHistoryScreen: 'GynecologicalHistoryScreen',
  ImmunizationScreen: 'ImmunizationScreen',
  PlanOfCareScreen: 'PlanOfCareScreen',
  MyHealth: 'MyHealth',
  Profile: 'Profile',
  ShlScreen: 'ShlScreen',
};
